apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen2-may5-2-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/codegen2-may5-2/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/codegen2-may5-2-gitops.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: codegen2-may5-2
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
