apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen2-may5-2
  janus-idp.io/tekton: codegen2-may5-2
  backstage.io/kubernetes-id: codegen2-may5-2
  backstage.io/kubernetes-namespace: codegen2-may5-2
  app.kubernetes.io/part-of: codegen2-may5-2
resources:
  - application-dev.yaml